ICT-WAS/SpringWebProject

home/src/main/java/com/ict/home/config/WebMvcConfig.java
home/src/main/java/com/ict/home/user/User.java
home/src/main/java/com/ict/home/user/UserController.java
home/src/main/java/com/ict/home/user/UserRepository.java
home/src/main/java/com/ict/home/user/UserService.java
home/src/main/java/com/ict/home/user/UserStatus.java
home/src/main/java/com/ict/home/util/BaseTimeEntity.java
react-home/home/src/components/user/User.jsx

* cors 설정
- config 파일 설정
* User 폴더 기본 구조 세팅
- util 패키지 생성일, 수정일, 생성자, 수정자 정보를 자동 관리해주는 클래스 생성. 해당 클래스를 상속받아 사용하면 클래스에 정의되어 있는 필드가 함께 생성됨.

cors  및 User 폴더 구조 세팅

---

react-home/home/src/apply_announcement/ApplyAnouncementContent.jsx
react-home/home/src/apply_announcement/ApplyAnouncementList.jsx
react-home/home/src/apply_announcement/ApplyAnouncementListContent.jsx
react-home/home/src/apply_announcement/NotificationButton.jsx
react-home/home/src/common/Common.css
react-home/home/src/common/Header.jsx
react-home/home/src/index.js

공고 페이지 css코드 변경

---

react-home/home/package-lock.json
react-home/home/package.json
react-home/home/src/apply_announcement/ApplyAnouncementListContent.jsx
react-home/home/src/apply_announcement/NotificationButton.jsx
react-home/home/src/common/Common.css
react-home/home/src/main/MainContent.jsx

알림 드롭다운 변경, 필터 페이지 검색 버튼 및 정렬 드롭다운 생성 레이아웃 추가

[리액트] 필터 페이지 수정 작업

---

home/src/main/java/com/ict/home/config/TokenInterceptor.java
home/src/main/java/com/ict/home/config/WebMvcConfig.java
home/src/main/java/com/ict/home/exception/BaseResponseStatus.java
home/src/main/java/com/ict/home/login/jwt/JwtProvider.java
home/src/main/java/com/ict/home/login/jwt/Token.java
home/src/main/java/com/ict/home/user/UserController.java
home/src/main/java/com/ict/home/user/UserRepository.java
home/src/main/java/com/ict/home/user/UserService.java
home/src/main/java/com/ict/home/user/UserUtilService.java
home/src/main/java/com/ict/home/util/BaseTimeEntity.java
react-home/home/package.json
react-home/home/src/api/TokenUtils.js
react-home/home/src/components/login/LoginStateButton.jsx
react-home/home/src/pages/Login.jsx

- React 로그인&로그아웃 버그 수정
데이터베이스에 등록되지 않은 사용자 로그인 시도 시 오류 처리
액세스토큰 재발급을 위한 전역 컴포넌트 생성 - 차후 수정 및 도입 예정
- Spring interseptor 클래스 생성
차후 로그인 접근 제한을 위한 interseptor 클래스 생성 - config 파일과 함께 수정 중

[React] 로그인&로그아웃 버그 수정 / util component [Spring] 접근제한 interseptor 클래스 생성

---

.gitignore
api-to-db/README.txt
api-to-db/api/file_test.py
api-to-db/api/getAPT.py
api-to-db/api/getAPTDetail.py
api-to-db/api/unique_test.py
api-to-db/database/APT 및 무순위 및 잔여세대 주택형별 insertDatabase.py
api-to-db/database/APT 분양정보 insertDatabase.py
api-to-db/database/무순위 및 잔여세대 분양정보 insertDatabase.py
api-to-db/info.txt
api-to-db/utility.py

api-to-db/README.txt : 사용 설명,
.gitignore : api-to-db/info.txt 추가

[Python] 주택청약 API 데이터 수집 및 DB 저장 기능 추가

---

react-home/home/src/apply_announcement/ApplyAnouncementListContent.jsx
react-home/home/src/apply_announcement/FilteredTag.jsx
react-home/home/src/apply_announcement/conditions.js
react-home/home/src/common/Common.css

- 필터 추가 및 삭제 기능
- 필터 조건 파일 생성
- array 로부터 만들어지는 태그에 key prop 추가
작업 예정 기능
- 선택된 필터 배경색 변경
- 지역 (군/구) 에서 전체 선택시 선택된 하위 지역 태그 제거

[리액트] 필터 페이지 필터 추가 및 삭제 기능

---

react-home/home/src/common/Header.jsx
react-home/home/src/condition/Condition01.jsx
react-home/home/src/condition/Condition01Content.jsx
react-home/home/src/condition/Condition02.jsx
react-home/home/src/condition/Condition03.jsx
react-home/home/src/condition/Conditions.jsx
react-home/home/src/condition/RadioButtonItem.jsx
react-home/home/src/condition/conditionItems.js
react-home/home/src/index.js

- Conditionxxx.jsx : 조건 등록 페이지 생성
- index.js, Header.jsx : 라우터 설정

조건 등록 페이지 생성 및 라우터 설정

---

api-to-db/final.sql

검토 여러 번 했습니다.
수정사항이나 개선사항 있으면 말씀해주십쇼! 
회의, 검토 후 반영하겠습니다!

[SQL] 테이블 생성 SQL 쿼리 추가

---

api-to-db/final.sql
home/build.gradle

SQL 및 gradle 수정
1. 경기 입주일 칼럼명 변경
2. build.gradle에 openAPI 추가

SQL 및 gradle 수정

---

api-to-db/final.sql
home/src/main/java/com/ict/home/condition/model/Condition01.java

경기 입주일 -> region_move_in_date ( 현재 지역 입주일 )

조건01 테이블 칼럼명 수정

---

api-to-db/final.sql
home/src/main/java/com/ict/home/community/controller/CommunityController.java
home/src/main/java/com/ict/home/community/model/Comment.java
home/src/main/java/com/ict/home/community/model/Post.java
home/src/main/java/com/ict/home/condition/enumeration/AccountType.java
home/src/main/java/com/ict/home/condition/model/Account.java
home/src/main/java/com/ict/home/condition/model/Condition01.java
home/src/main/java/com/ict/home/condition/model/Condition02.java
home/src/main/java/com/ict/home/condition/model/Condition03.java
home/src/main/java/com/ict/home/condition/model/Family.java
home/src/main/java/com/ict/home/house/model/Detail.java
home/src/main/java/com/ict/home/house/model/Detail01.java
home/src/main/java/com/ict/home/house/model/Detail04.java
home/src/main/java/com/ict/home/house/model/House.java
home/src/main/java/com/ict/home/user/User.java
home/src/main/resources/application.properties

- member -> user 변경
- 2지선다 칼럼들 Boolean 타입으로 변경
- Entity 클래스에서 참조관계, 컨버터, Null 여부 설정 후 데이터베이스 연동
- AccountType 오타 수정
- 데이터베이스 정보 변경

[데이터베이스 및 스프링 Entity 수정]

---

home/src/main/java/com/ict/home/house/controller/HouseController.java
home/src/main/java/com/ict/home/house/service/HouseServiceImpl.java
react-home/home/src/apply_announcement/ApplyAnouncementListContent.jsx
react-home/home/src/common/Common.css

- 구현 완료: pagination, 데이터 처리
- 추가 예정: 조건 페이지, 기능 완료 후 조건별 공고 보기 구현 예정

[React] 공고 목록 페이지 구현 (조건 완료 후 추가 필요)

---

api-to-db/final.sql
home/src/main/java/com/ict/home/community/controller/CommunityController.java
home/src/main/java/com/ict/home/community/model/Comment.java
home/src/main/java/com/ict/home/community/service/CommunityService.java
home/src/main/java/com/ict/home/condition/model/Condition03.java
react-home/home/src/common/Header.jsx
react-home/home/src/community/CommunityCard.jsx
react-home/home/src/index.js
react-home/home/src/main/MainContent.jsx

- 페이지네이션
- 게시글 등록: 로그인 상태 확인
- 제목 검색 기능

[React] 커뮤니티 게시글 목록 페이지 구현 완료

---

home/src/main/java/com/ict/home/community/controller/CommunityController.java
react-home/home/src/community/CommunityCard.jsx

커뮤니티 게시글 목록 페이지 작성자, 날짜 표기법 수정

커뮤니티 게시글 목록 페이지 작성자, 날짜 표기법 수정

---

react-home/home/src/components/signup/Email.jsx
react-home/home/src/components/signup/phone.jsx
react-home/home/src/index.js

- 회원가입 실패 오류 해결
리액트 컴포넌트 초기화 관련 영역 삭제

[React] 회원가입 오류 수정

---

home/src/main/java/com/ict/home/community/model/Comment.java
home/src/main/java/com/ict/home/community/model/Post.java
home/src/main/java/com/ict/home/condition/model/Account.java
home/src/main/java/com/ict/home/condition/model/Condition01.java
home/src/main/java/com/ict/home/condition/model/Condition03.java
home/src/main/java/com/ict/home/condition/model/Family.java
home/src/main/java/com/ict/home/house/model/Detail.java
home/src/main/java/com/ict/home/house/model/Detail01.java
home/src/main/java/com/ict/home/house/model/Detail04.java
home/src/main/java/com/ict/home/house/model/House.java
home/src/main/java/com/ict/home/interest/model/Interest.java

[스프링] 참조 무결성 제약조건 설정 및 interest Entity 추가

---

home/src/main/java/com/ict/home/notification/controller/NotificationController.java
home/src/main/java/com/ict/home/notification/enumeration/NotificationType.java
home/src/main/java/com/ict/home/notification/model/Notification.java
home/src/main/java/com/ict/home/notification/repository/NotificationRepository.java
home/src/main/java/com/ict/home/notification/service/NotificationService.java
home/src/main/java/com/ict/home/notification/service/NotificationServiceImpl.java

[스프링] 알림 기능 구현 완료

---

react-home/home/src/main/MainContent.jsx
react-home/home/src/main/MainPostCard.jsx

화면 넘김 해결
좌우로 드래그 허용
드래그 시 글자 선택 방지

[리액트] 메인페이지 게시글 목록 디자인 변경

---

react-home/home/src/common/Footer.jsx
react-home/home/src/main/MainContent.jsx
react-home/home/src/main/MainPostCard.jsx

저희 협업할 때 사용했던 툴들 링크나 
학원 정보 등 연결해두었습니다.

[리액트] 푸터 정보 변경

---

react-home/home/src/community/PostDetailContent.jsx

수정과 삭제시 문제가 있던 것을 해결하였습니다.
대댓글의 경우에도 답글들을 찾는 부분을 변경했습니다.

[리액트] 댓글 버그 수정 완료

---

home/src/main/java/com/ict/home/HomeApplication.java
home/src/main/java/com/ict/home/community/repository/CommentRepository.java
home/src/main/java/com/ict/home/community/service/CommunityServiceImpl.java
home/src/main/java/com/ict/home/notification/model/Notification.java
home/src/main/java/com/ict/home/notification/service/NotificationServiceImpl.java

- 관심 공고의 접수 시작일, 종료일, 당첨자 발표일에 알림을 보내는 기능 구현
- 커뮤니티 댓글, 답글 작성시 연관된 유저들에게 알림 보내는 기능 구현

[스프링] 관심 공고 일정별, 커뮤니티 관련 알림 구현 완료

---

home/src/main/java/com/ict/home/house/controller/HouseController.java
react-home/home/src/apply_announcement/AnnouncementLocationMap.jsx
react-home/home/src/apply_announcement/ApplyAnouncementContent.jsx
react-home/home/src/index.js

리액트에서 스프링으로 위치 정보를 넘긴 뒤
네이버지도 API 지오코드 결과의 위도, 경도를 다시 스프링으로 응답받은 결과를 시각화

[리액트, 스프링] 네이버지도 API 지오코드 => 지도 시각화

---

home/src/main/java/com/ict/home/house/utility/PostalCodeFind.java

지역별 우편번호 추가 - 세종특별자치시

---

react-home/home/src/apply_announcement/ApplyAnnouncementList.jsx
react-home/home/src/apply_announcement/ApplyAnnouncementListContent.jsx
react-home/home/src/apply_announcement/SearchAnnouncementByName.jsx
react-home/home/src/community/PostDetailContent.jsx
react-home/home/src/condition/Condition01Content.jsx
react-home/home/src/condition/Condition02Content.jsx
react-home/home/src/condition/Condition03Content.jsx
react-home/home/src/condition/Conditions.jsx
react-home/home/src/index.js

조건 등록 페이지, 조건 검색 '내 조건으로 검색' 권한 확인, 
오타 수정
댓글수정 버그 고침

[리액트] 조건 등록 페이지, 조건 검색 '내 조건으로 검색' 권한 확인, 오타 수정

---

home/src/main/java/com/ict/home/house/controller/HouseController.java
home/src/main/java/com/ict/home/house/service/HouseService.java
home/src/main/java/com/ict/home/house/service/HouseServiceImpl.java
react-home/home/src/apply_announcement/ApplyAnouncementContent.jsx
react-home/home/src/apply_announcement/RecommandedButton.jsx
react-home/home/src/apply_announcement/SupplySolution.jsx

공고 종류 : 일반(민영, 국민), 무순위
공급 방식 : 일반 공급 ( 1순위, 2순위 ), 특별 공급 ( 다자녀가구, 신혼부부, 생애최초, 노부모부양, 기관추천, 기타, 이전기관, 청년, 신생아)
공고별 공급 방식에서 요구하는 지원 자격을 회원의 조건을 조회하여 판단하여서
충족하는 점, 충족하지 못하는 점을 분류하여 나타내고, 이에 따른 솔루션을 제공하였습니다.

공고 종류, 공급 방식, 회원의 조건에 따른 맞춤형 솔루션 구현 완료
